os: Visual Studio 2015

# Clone directly into GOPATH.
clone_folder: C:\gopath\src\github.com\dh1tw\streamdeck
clone_depth: 1
version: "{branch}.{build}"
environment:
  global:
    GOPATH: C:\gopath
    CC: gcc.exe
  matrix:
    - GOARCH: amd64
      GOOS: windows
      MSYS2_ARCH: x86_64
      MSYS2_BITS: 64
      MSYSTEM: MINGW64
      PATH: C:\msys64\mingw64\bin\;%PATH%
    - GOARCH: 386
      GOOS: windows
      MSYS2_ARCH: i686
      MSYS2_BITS: 32
      MSYSTEM: MINGW32
      PATH: C:\msys64\mingw32\bin\;%PATH%

install:
  - rmdir C:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go1.10.8.windows-%GOARCH%.zip
  - 7z x go1.10.8.windows-%GOARCH%.zip -y -oC:\ > NUL
  - go version
  - gcc --version

build_script:
  - go get ./...
  - go get github.com/gobuffalo/packr/v2/packr2
  - set PATH=%PATH%;C:\gopath\bin
  - packr2
  - dir
  - go build examples/enumerate.go
  - go build examples/icons.go
  - go build examples/labels.go
  - go build examples/led_buttons.go
  - go build examples/pages.go
  - go build examples/slideshow.go
  - go build examples/textbuttons.go
  - dir
  - 7z a -tzip streamdeck-v$APPVEYOR_REPO_TAG_NAME-$GOOS-$GOARCH.zip *.exe

artifacts:
  - path: streamdeck-v$APPVEYOR_REPO_TAG_NAME-$GOOS-$GOARCH.zip
    name: streamdeck